<?php

require_once(dirname(__FILE__).'/../../../config/config.php');
require_once 'PHPUnit.php';
require_once 'src/dao/BillDAO.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-19 at 20:38:29.
 */
class BillDAOTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var BillDAO
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BillDAO;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * Generated from @assert (1,1) == 2.
     *
     * @covers BillDAO::addTwoNumbers
     */
    public function testAddTwoNumbers()
    {
        $this->assertEquals(
                2, $this->object->addTwoNumbers(1, 1)
        );
    }

    /**
     * Generated from @assert (1,2) == 3.
     *
     * @covers BillDAO::addTwoNumbers
     */
    public function testAddTwoNumbers2()
    {
        $this->assertEquals(
                3, $this->object->addTwoNumbers(1, 2)
        );
    }

    /**
     * Generated from @assert (1,3) == 4.
     *
     * @covers BillDAO::addTwoNumbers
     */
    public function testAddTwoNumbers3()
    {
        $this->assertEquals(
                4, $this->object->addTwoNumbers(1, 3)
        );
    }

    /**
     * Generated from @assert (1,4) == 5.
     *
     * @covers BillDAO::addTwoNumbers
     */
    public function testAddTwoNumbers4()
    {
        $this->assertEquals(
                5, $this->object->addTwoNumbers(1, 4)
        );
    }

}
