<?php

require_once(dirname(__FILE__).'/../../config/config.php');
require_once 'unittest/TestCaseBase.php';
require_once 'src/dao/BillSubjectMongoDAO.php';
require_once 'src/dao/MongoDatabase.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-19 at 20:38:29.
 */
class BillDAOTest extends TestCaseBase
{


    private function getMockMongo()
    {
        return $this->getMock('Mongo',
                array('selectCollection'),array());
    }

    private function getMockMongDB($mockMongo)
    {
        return $this->getMock('MongoDB',
                array('insert'),array($mockMongo,'mock'));
    }

    private function getMockMongoCollection($mockMongoDB)
    {
        return $this->getMock('MongoCollection',
                array('insert'),array($mockMongoDB,'mock'));
    }

    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testConnectToDB()
    {
        $mongo = MongoDatabase::createMongoDatabase("crowd", "source",
                                                    "localhost", "billsubject");
    }

    public function testConnectToDBBad()
    {
        $this->setExpectedException('MongoConnectionException');
        $mongo = MongoDatabase::createMongoDatabase("zzz", "sourcez",
                                                    "localhost", "billsubject");
    }

    public function testAddBill()
    {
        $bill = array('subject' => 'lulz');

        $mockMongo = $this->getMockMongo();
        $mockMongoDB = $this->getMockMongDB($mockMongo);
        $mockMongoCollection = $this->getMockMongoCollection($mockMongoDB);

        $mockMongo->expects($this->once())
             ->method('selectCollection')
             ->will($this->returnValue($mockMongoCollection))
             ->with($this->equalTo('bills'));
        $mockMongoCollection->expects($this->once())
             ->method('insert')
             ->will($this->returnValue(true))
             ->with($this->equalTo($bill));

        $billDAO = new BillSubjectMongoDAO($mockMongo);
        $billDAO->addBill($bill);
    }

    public function testAddBillMissingSubject()
    {
        $bill = array();

        $mockMongo = $this->getMockMongo();
        $mockMongoDB = $this->getMockMongDB($mockMongo);
        $mockMongoCollection = $this->getMockMongoCollection($mockMongoDB);

        $mockMongo->expects($this->never())
             ->method('selectCollection');

        $this->setExpectedException('ParameterCheckException');
        $billDAO = new BillSubjectMongoDAO($mockMongo);
        $billDAO->addBill($bill);
    }

    public function testUpdateBill()
    {
        $this->fail('Not yet implemented');
    }

    public function testRemoveUpdateBill()
    {
        $this->fail('Not yet implemented');
    }


    public function testAddUser()
    {
        $user = array( 'username' => 'lulz', 'password' => 'lulz');

        $mockMongo = $this->getMockMongo();
        $mockMongoDB = $this->getMockMongDB($mockMongo);
        $mockMongoCollection = $this->getMockMongoCollection($mockMongoDB);

        $mockMongo->expects($this->once())
             ->method('selectCollection')
             ->will($this->returnValue($mockMongoCollection))
             ->with($this->equalTo('users'));
        $mockMongoCollection->expects($this->once())
             ->method('insert')
             ->will($this->returnValue(true))
             ->with($this->equalTo($user));

        $billDAO = new BillSubjectMongoDAO($mockMongo);
        $billDAO->addUser($user);
    }

    public function testAddUserBad()
    {

    }

    public function testUpdateUser()
    {
        $this->fail('Not yet implemented');
    }

    public function testRemoveUpdateUser()
    {
        $this->fail('Not yet implemented');
    }

}
