<?php

require_once(dirname(__FILE__).'/../../config/config.php');
require_once 'PHPUnit/Autoload.php';
require_once 'src/dao/BillDAO.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-19 at 20:38:29.
 */
class BillDAOTest extends PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * Generated from @assert (1,1) == 2.
     *
     * @covers BillDAO::addTwoNumbers
     */
    public function testAddTwoNumbers()
    {
        $mockMongo = $this->getMock('MongoDatabase');
        $billDAO = new BillDAO($mockMongo);
        $this->assertEquals(
                2, $billDAO->addTwoNumbers(1, 1)
        );
    }

    public function testAddBill()
    {
        $mockMongo = $this->getMock('Mongo', array('selectDB'));
        $mockMongo->expects($this->once())
             ->method('selectDB')
             ->will($this->returnValue(true));


    }

}
